rfi/excelfiles/urls.py
from django.urls import path
from . import views

app_name = 'excelfiles'

urlpatterns = [
    path('get-rfis/', views.get_rfis, name='get_rfis'),
    path('print-page/', views.print_page, name='print_page'),
    path('create-request/', views.create_request_list, name='create_request'),
    path('from-django-to-excel/',
         views.from_django_to_excel, name='from_django_to_excel'),
    path('create_rfi/', views.create_rfi, name='create_rfi'),
    path('eftb/', views.excel_file_to_browser, name="excel_file_to_browser"),
    path('fill_rfi_numbers/', views.process_excel_file, name='fill_rfi_numbers'),
    path('success/', views.success_page, name='success'),
    path('rubka/', views.dispathcher, name='rubka'),
    path('create_daily_rfis/', views.create_daily_rfis, name='create_daily_rfis'),
    path('get_info/', views.get_information, name='get_info'),
    #path('convert_excel_to_pdf_view/', views.convert_excel_to_pdf_view, name='convert_excel_to_pdf_view'),
]

rfi/rfi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

#Содержит все пути приложений

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rficrud.urls', namespace='rficrud')),
    path('', include('excelfiles.urls', namespace='excelfiles_test')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),

]

rfi/rficrud/urls.py
from django.urls import path, include
from . import views
from.views import DefaultSignersConstructionViewSet, \
    RFIViewSet, ProjectViewSet, CustomTokenObtainPairView
from rest_framework.routers import DefaultRouter
from .autocomplete import ObjectAutocomplete
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
app_name = 'rficrud'

#Содержит все пути для отображения только на ознакомление с информацией

router = DefaultRouter()
router.register('defualt-signers', DefaultSignersConstructionViewSet, basename='defualt-signers')
router.register(r'rfis', RFIViewSet, basename='rfis')
router.register('projects', ProjectViewSet, basename='projects')

urlpatterns = [
    path('', views.mainpage, name='index'),
    path('rfi_list/', views.rfi_list, name="rfi_list"),
    path('get_projects_by_object/<int:object_id>/', views.get_projects_by_object, name='get_projects_by_object'),
    #path('slug_create', views.slug_create, name='slug_create'),
    path('rfi_list/<slug:rfi_slug>/', views.single_rfi_read, name='single_rfi_read'),
    path('rfi_list/<slug:rfi_slug>/add_comment/', views.add_comment, name='add_comment'),
    path('update_status/<int:rfi_id>/<str:new_status>/', views.update_rfi_status, name='update_rfi_status'),
    path('inspector/<str:username>/', views.inspector_view, name='inspector_view'),
    path('search/', views.search, name="search"),
    path('rfi_create/', views.RFICreateView.as_view(), name='rfi_create'),
    path('object_autocomplete/', ObjectAutocomplete.as_view(), name='object_autocomplete'),
    path('api/', include(router.urls)),
    #path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair')
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

rfi/excelfiles/models.py
from django.db import models

# Create your models here.

rfi/excelfiles/forms.py
from django import forms
from rficrud.models import RFI, Construction, Project, RelationAkkuyuRFI, RelationIndependentRFI, RelationQaSignerRFI, RelationSupervisionRFI, Contractor
from django.forms.widgets import DateInput


class RfiFilterForm(forms.Form):
    object_name = forms.CharField(label='Object Name', required=False)
    project_name = forms.CharField(label='Project Name', required=False)
    date_of_create = forms.DateField(label='Date of Create', required=False, widget=DateInput(attrs={'type': 'date'}))
    status = forms.ChoiceField(label='Status', required=False, choices=[('', '---------')] + RFI.status_list)


class RFIForm(forms.ModelForm):
    class Meta:
        model = RFI
        fields = ['object_name', 'project_name', 'akkuyu_signer', 'independent_control', 'qc_signer', 'design_supervision_signer', 'contractor']


class NumberRangeForm(forms.Form):
    from_number = forms.IntegerField(label='From number', required=True)
    to_number = forms.IntegerField(label='To number', required=True)

rfi/excelfiles/views.py
import datetime
import pytz
import win32com.client as win32
import win32print
import pythoncom
import csv
import textwrap

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle

from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required
from rficrud.models import RFI, Inspector
from django.shortcuts import render, redirect, get_object_or_404
from datetime import date
import openpyxl
from openpyxl.utils import rows_from_range
import os
from .forms import RFIForm, NumberRangeForm

local_path_to_templates = 'excelfiles/all_excel_files/excel_templates/'

local_tz = pytz.timezone('Europe/Moscow')
today_date = date.today()
#today_date = date(2023, 8, 10)
current_month = today_date.strftime("%m_%B")
current_year = today_date.strftime("%Y")
PATH_TO_SAVE = f'excelfiles/all_excel_files/{current_year}/{current_month}/'


save_today_date = today_date.strftime('%d-%m-%Y')

base_path = "C:/Users/Maksim/PycharmProjects/Django_Rfi/rfi/"


@login_required
def process_excel_file(request):
    """Func that get excel file with RFI numbers from JV and set it to DataBase"""
    if request.method == 'POST':
        excel_file = request.FILES['excel_file']
        wb = openpyxl.load_workbook(filename=excel_file, read_only=True)
        ws = wb.active

        last_row = ws.max_row
        # print(last_row)
        req_date = ws['C2'].value
        if req_date:
            daily_rfis = RFI.objects.filter(date_of_inspection__date=req_date)
            for row_index, row in enumerate(ws.iter_rows(min_row=2, max_row=last_row), start=2):
                try:
                    desc_of_work = ws[f"H{row_index}"].value
                    desc_of_work = desc_of_work.split('#')[0].strip()
                    print(type(desc_of_work), row_index, desc_of_work)
                    temporary_rfi = daily_rfis.get(description_of_work_russian=desc_of_work)
                    print(temporary_rfi.description_of_work_english)
                    number = ws[f'A{row_index}'].value[-5:]
                    temporary_rfi.rfi_number_from_akkuyu = int(number)
                    temporary_rfi.save()
                except:
                    pass
            messages.success(request, f"The operation was completed with Success!")
            return redirect('/success')

    return render(request, 'excelfiles/fill_rfi_numbers.html')


def success_page(request):
    return render(request, 'excelfiles/success.html')


def excel_file_to_browser(request):
    return render(request, 'excelfiles/excel_file_to_browser.html')


@require_GET
def get_rfis(request):
    """Функция возвращает JSON всех ЗНО

       СДЕЛАТЬ!!!
            фильтрацию перед выдачей, дать поля для выдачи
        """
    rfis = RFI.objects.all()
    data = []
    for rfi in rfis:
        data.append({
            'id': rfi.id,
            'excel_number': rfi.excel_number,
            # #'status': rfi.status,
            # 'rfi_number_from_akkuyu': rfi.rfi_number_from_akkuyu,
            # 'date_of_create': rfi.date_of_create.strftime('%Y-%m-%d'),
            # 'date_of_inspection': rfi.date_of_inspection.strftime('%Y-%m-%d'),
            # 'object_name': rfi.object_name.name,
            # 'project': rfi.project,
            # 'type_of_work': rfi.type_of_work,
            # 'description_of_work_russian': rfi.description_of_work_russian,
            # 'description_of_work_english': rfi.description_of_work_english,
            # 'quality_plan_code': rfi.quality_plan_code,
            # 'akkuyu_signer': rfi.akkuyu_signer.name,
            # 'independent_control': rfi.independent_control.name,
            # 'qc_signer': rfi.qc_signer.name,
            # 'design_supervision_signer': rfi.design_supervision_signer.name,
            # 'contractor': rfi.contractor.name if rfi.contractor else '',
            # 'contractor_sintek': rfi.contractor_sintek.name if rfi.contractor_sintek else '',
        })
    return JsonResponse(data, safe=False)


def from_django_to_excel(request):
    #today_date = date(2023, 6, 10)
    rfi_list = RFI.objects.filter(date_of_create__date=today_date)
    excel_template_path = local_path_to_templates + 'from_django_to_excel_template.xlsx'

    try:
        workbook = openpyxl.load_workbook(excel_template_path)
        worksheet = workbook.active

        row = 2
        row_height = 100
        for rfi in rfi_list:
            check_inspector(rfi)
            worksheet[f'C{row}'] = rfi.object_name.object_name
            worksheet[f'D{row}'] = rfi.project_name.name()
            worksheet[f'E{row}'] = rfi.description_of_work_russian
            worksheet[f'F{row}'] = rfi.description_of_work_english
            worksheet[f'I{row}'] = rfi.date_of_create.date()
            worksheet[f'J{row}'] = rfi.date_of_inspection.date()
            localized_inspection_time = rfi.date_of_inspection.astimezone(local_tz)
            worksheet[f'K{row}'] = localized_inspection_time.time()
            localized_create_time = rfi.date_of_create.astimezone(local_tz)
            worksheet[f'L{row}'] = localized_create_time.time()
            worksheet.row_dimensions[row].height = row_height

            if rfi.rfi_number_from_akkuyu:
                worksheet[f'H{row}'] = "ЗНО-" + str(rfi.rfi_number_from_akkuyu)
                # print(rfi.rfi_number_from_akkuyu, type(rfi.rfi_number_from_akkuyu))

            if rfi.is_active_beton:
                worksheet[f'G{row}'] = '+'

            row += 1

        print('HELLO GABE')

        folder_name = check_folder_exist()
        workbook.save(f'{folder_name}/From_django_to_Excel_{save_today_date}.xlsx')
        messages.success(request, f'File From_django_to_Excel_{save_today_date} Created')
    except FileNotFoundError:
        messages.error(request, f'File From_django_to_Excel_{save_today_date} failed')
        print('cant find file')

    # return redirect('print_page')
    return redirect('/rubka')


def dispathcher(request):
    form = NumberRangeForm()
    return render(request, 'excelfiles/dispathcher.html', {"form": form})


def print_page(request):
    """Начальная стадия контроллера для Создания и печати Excel файлов"""

    return render(request, 'excelfiles/print_page.html')


def create_json_answer(queryset):
    data = []
    for rfi in queryset:
        data.append({
            'id': rfi.id,
            'excel_number': rfi.excel_number,
            # #'status': rfi.status,
            # 'rfi_number_from_akkuyu': rfi.rfi_number_from_akkuyu,
            # 'date_of_create': rfi.date_of_create.strftime('%Y-%m-%d'),
            # 'date_of_inspection': rfi.date_of_inspection.strftime('%Y-%m-%d'),
            'object_name': rfi.object_name.object_name,
            # 'project': rfi.project.project_name,
            # 'type_of_work': rfi.type_of_work,
            # 'description_of_work_russian': rfi.description_of_work_russian,
            'description_of_work_english': rfi.description_of_work_english,
            # 'quality_plan_code': rfi.quality_plan_code,
            # 'akkuyu_signer': rfi.akkuyu_signer.name,
            # 'independent_control': rfi.independent_control.name,
            # 'qc_signer': rfi.qc_signer.name,
            # 'design_supervision_signer': rfi.design_supervision_signer.name,
            # 'contractor': rfi.contractor.name if rfi.contractor else '',
            # 'contractor_sintek': rfi.contractor_sintek.name if rfi.contractor_sintek else '',
        })
    return data


def create_request_list_tool(queryset, path_to_template):
    """Получает QuerySet, Путь до шаблона на основе этих данных формирует заявку на инспекцию
    """
    insp_date = queryset.last().date_of_inspection.strftime('%d-%m-%Y')
    try:
        print('Стартую')
        workbook = openpyxl.load_workbook(path_to_template)
        print('It works')
        worksheet = workbook.active
        # print(type(worksheet))

        row = 2
        row_height = 80
        #print(queryset)
        obj_name_dict = {}
        for rfi in queryset:
            print(rfi.project_name)
            print(f"Filing {row}'nd row")
            worksheet[f'B{row}'] = rfi.date_of_create.date()
            worksheet[f'C{row}'] = rfi.date_of_inspection.date()
            localozed_time = rfi.date_of_inspection.astimezone(local_tz)
            worksheet[f'D{row}'] = localozed_time.time()

            worksheet[f'E{row}'] = rfi.object_name.object_name

            worksheet[f'H{row}'] = rfi.description_of_work_russian + ' # ' + rfi.description_of_work_english
            worksheet[f'I{row}'] = rfi.project_name.quality_plan.quality_plan_name

            project = rfi.project_name
            worksheet[f'F{row}'] = f'{project.constriction_object}.' \
                                   f'{project.code}.{project.object_name}.' \
                                   f'{project.type_of_works}.{project.project_name}'
            worksheet[f'G{row}'] = rfi.object_name.object_place
            if rfi.pk_points:
                worksheet[f"J{row}"] = rfi.pk_points
            else:
                worksheet[f"J{row}"] = 'H-H-H-H'
            worksheet[f'M{row}'] = rfi.akkuyu_signer.signer_name
            worksheet[f'N{row}'] = rfi.independent_control.signer_name
            worksheet[f'O{row}'] = rfi.qc_signer.signer_name
            worksheet[f'P{row}'] = rfi.contractor.signer_name
            worksheet[f'R{row}'] = rfi.contractor_sintek
            worksheet[f'S{row}'] = rfi.design_supervision_signer.signer_name
            worksheet[f'V{row}'] = 'TSM ENERJI (Sintek)'
            worksheet.row_dimensions[row].height = row_height

            if rfi.object_name.object_name not in obj_name_dict:
                obj_name_dict[rfi.object_name.object_name] = 1

            copy_row_style(worksheet[2], worksheet[row])

rfi/templates/excelfiles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <!-- Add Bootstrap 4 CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Add custom CSS, if needed -->
    {% block custom_css %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Ведомость ЗНО Sintek</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rficrud:rfi_list' %}">Ведомость</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'excelfiles:rubka' %}">Диспечерская</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Придумать назначение</a>
                    </li>
                    <!-- Add more navigation items here -->
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-3">
        {% block content %}{% endblock %}
        {% block message %}{% endblock %}
    </div>


    {% block table %}
    {% endblock %}

    <!-- Add jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO+KRAJMI/zlgnbyaGRW1x8zONYMN1jMihibNTFh5G3f8KNuiajK5roTOmX9" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Add custom JS, if needed -->
    {% block custom_js %}{% endblock %}
</body>
</html>

rfi/templates/excelfiles/create_rfi.html
{% extends 'excelfiles/base.html' %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'excelfiles/css/create_rfi.css' %}">
{% endblock %}

{% block content %}
  <h1>Create RFI</h1>
<form method="post">
  {% csrf_token %}

  <div>
    <label for="object">Object:</label>
    <select id="object" name="object">
      <!-- Render the object options here -->
    </select>
  </div>

  <div>
    <label for="project">Project:</label>
    <select id="project" name="project">
      <!-- Render the project options here -->
    </select>
  </div>

  <div>
    <label for="inspection_date">Date and Time of Inspection:</label>
    <input type="datetime-local" id="inspection_date" name="inspection_date">
  </div>

  <div>
    <label for="points">Points from PK:</label>
    <select id="points" name="points">
      <!-- Render the points options here -->
    </select>
  </div>

  <div>
    <label for="type_of_works">Type of Works:</label>
    <input type="text" id="type_of_works" name="type_of_works">
  </div>

  <div>
    <label for="description">Description of Work:</label>
    <textarea id="description" name="description"></textarea>
  </div>

  <!-- Render the signer fields here -->

  <button type="submit">Create</button>
</form>

{% endblock %}

{% block custom_js %}
  <script src="{% static '/excelfiles/js/create_rfi.js' %}"></script>
{% endblock %}

rfi/templates/excelfiles/dispathcher.html
{% extends 'excelfiles/base.html' %}
{% load static %}

{% block title %}Диспечерская{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'excelfiles/css/messages.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <h2 class="mb-4">Диспечерская</h2>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a href="{% url 'excelfiles:create_request' %}" class="btn btn-primary">Create daily request</a>
        <a href="{% url 'excelfiles:fill_rfi_numbers' %}" class="btn btn-primary">Fill numbers from excel file</a>
        <a href="{% url 'excelfiles:from_django_to_excel' %}" class="btn btn-primary">Create excel file to fill excel book</a>
        <a href="{% url 'excelfiles:create_daily_rfis' %}" class="btn btn-primary">Create daily RFIs and Checklists</a>
        <a href="{% url 'excelfiles:success' %}" class="btn btn-primary">Print daily RFIs and Checklists</a>
        <a href="{% url 'excelfiles:excel_file_to_browser' %}" class="btn btn-primary">Show excel file</a>
    </div>
    <form action="{% url 'excelfiles:get_info' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>
</div>
{% endblock %}

{% block message %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

rfi/templates/excelfiles/excel_file_to_browser.html
{% extends 'excelfiles/base.html' %}
{% load static %}

{% block custom_css %}
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  integrity="sha384-pzjw8f+ua7Kw1TIq0v8FqFjcJ6pajs/rfdfs3SO+kD4Ck5BdPtF+to8xMmcke07g"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'excelfiles/css/excel_file_to_browser.css' %}">
{% endblock %}

{% block table %}
<input type="file" id="input-excel" />

<div id="excel-data"></div>
{% endblock %}

{% block custom_js %}
  <script src="{% static '/excelfiles/js/excel_file_to_browser.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>
{% endblock %}

rfi/templates/excelfiles/fill_rfi_numbers.html
{% extends 'excelfiles/base.html' %}
{% load static %}

{% block custom_css %}
{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="excel_file">
    <button type="submit">Submit</button>
</form>
{% endblock %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block custom_js %}
{% endblock %}

rfi/templates/excelfiles/from_django_to_excel.html
{% extends 'excelfiles/base.html' %}
{%load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'excelfiles/css/create_rfi.css' %}">
    <link rel="stylesheet" href="{% static 'excelfiles/css/messages.css' %}">
{% endblock %}

{% block message %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

rfi/templates/excelfiles/print_page.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Daily Requests</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
		}
		h1 {
			text-align: center;
		}
		form {
			display: flex;
			flex-direction: column;
			align-items: center;
			margin-top: 50px;
		}
		label {
			margin-bottom: 10px;
			font-weight: bold;
		}
		input[type="text"], input[type="date"] {
			padding: 10px;
			margin-bottom: 20px;
			border: 1px solid #ccc;
			border-radius: 4px;
			width: 300px;
		}
		button {
			background-color: #4CAF50;
			color: white;
			padding: 12px 20px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
			margin-bottom: 20px;
		}
		button:hover {
			background-color: #45a049;
		}
		#print-button {
			display: none;
			margin-top: 20px;
		}
		table {
			border-collapse: collapse;
			width: 100%;
			margin-top: 50px;
		}
		th, td {
			text-align: left;
			padding: 8px;
			border-bottom: 1px solid #ddd;
		}
		th {
			background-color: #4CAF50;
			color: white;
		}
		tr:hover {
			background-color: #f5f5f5;
		}
	</style>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#create-rfi').click(function() {
                $.getJSON('/get-rfis/', function(data) {
                    // `data` содержит JSON-ответ от сервера
                    // Вы можете перебрать список RFIs и отобразить их на своей странице
                    $.each(data, function(index, rfi) {
                        // `rfi` - это словарь, который содержит данные RFI
                        // Вы можете получить доступ к данным, используя ключи в словаре, например, rfi.id, rfi.excel_number, и т.д.
                        // Используйте jQuery для обновления вашего HTML для отображения данных RFI по желанию
                        $('#rfi-list').append('<li>RFI ' + rfi.id + ': ' + rfi.excel_number + '</li>');
                    });
                });
            });
        });
    </script>
</head>
<body>
	<h1>Daily Requests</h1>
	<form>
		<label for="date">Date:</label>
		<input type="date" id="date" name="date">

		<label for="excel-number">Excel Number:</label>
		<input type="text" id="excel-number" name="excel-number">

		<label for="rfi-number">RFI Number:</label>
		<input type="text" id="rfi-number" name="rfi-number">

		<button type="button" id="create-request">Create Daily Request</button>
		<button type="button" id="create-rfi">Create Daily RFI</button>
		<button type="button" id="print-rfi" disabled>Print Daily RFI</button>
	</form>
	<ul id="rfi-list">

	</ul>
	<table id="rfi-table" style="display: none;">
		<thead>
			<tr>
				<th>Excel Number</th>
				<th>RFI Number</th>
				<th>Date</th>
				<th>Field 1</th>
				<th>Field 2</th>
				<th>Field 3</th>
				<th>Field 4</th>
				<th>Field 5</th>
				<th>Field 6</th>
			</tr>
		</thead>
		<tbody>
			<!-- Table data will be dynamically added here -->
		</tbody>
	</table>



</body>


</html>

rfi/templates/excelfiles/success.html
{% extends 'excelfiles/base.html' %}
{% load static %}


{% block custom_css %}
    <link rel="stylesheet" href="{% static 'excelfiles/css/create_rfi.css' %}">
    <link rel="stylesheet" href="{% static 'excelfiles/css/messages.css' %}">
{% endblock %}


{% block message %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<script>
    setTimeout(function() {
        window.location.href = "{% url 'rficrud:index' %}";
    }, 5000); // 5000 миллисекунд = 5 секунд
</script>
{% endblock %}